# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Mathematical Foundations of Data Science
author: Mahmood Amintoosi
logo: img/fum-cs-logo.png
copyright: "2026. CC0 Licensed - Computer Science Dept., Ferdowsi University of Mashhad"

execute:
  execute_notebooks: off
  timeout: -1
  exclude_patterns:
    - 'S*'
    - markdown
    - notebooks
    - markdown-notebooks
    - temp/*
    - APP*
    - learning/lecture*

latex:
  latex_documents:
    targetname: MFDS.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/fum-cs/mfds
  path_to_book: notebooks
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  favicon: img/fum-logo.ico
  extra_navbar: ""

launch_buttons:
  colab_url: "https://colab.research.google.com"
